export const dummy = [
  {
    _id: "63e10d41546bb81111ff6cbd",
    index: 0,
    guid: "b7bc4bb5-e0eb-4757-9949-c1bbb67280b1",
    isActive: true,
    balance: "$1,220.26",
    picture: "http://placehold.it/32x32",
    age: 24,
    eyeColor: "green",
    name: "Noel Cohen",
    gender: "male",
    company: "VIRXO",
    email: "noelcohen@virxo.com",
    phone: "+1 (802) 575-2344",
    address: "123 Adelphi Street, Boykin, Rhode Island, 4152",
    about:
      "Non ipsum ipsum ad consectetur elit elit incididunt ex cupidatat deserunt. Sint exercitation et sunt ut occaecat anim dolore veniam elit eiusmod aliqua. Fugiat aliqua laborum aliqua voluptate nisi enim tempor quis dolore eiusmod. Cillum incididunt dolore excepteur fugiat eu occaecat enim commodo. Consectetur culpa sit sit proident qui sunt ad sit exercitation id.\r\n",
    registered: "2017-11-04T04:53:41 -06:-45",
    latitude: -84.319059,
    longitude: -46.400276,
    tags: ["eu", "ea", "sint", "officia", "labore", "ipsum", "sit"],
    friends: [
      {
        id: 0,
        name: "Schwartz Dickerson",
      },
      {
        id: 1,
        name: "Merritt Gentry",
      },
      {
        id: 2,
        name: "Rosemary Stanley",
      },
    ],
    greeting: "Hello, Noel Cohen! You have 8 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "63e10d41c6593ab424b0bf33",
    index: 1,
    guid: "bdcb02ed-0792-4e2c-a8b0-218323b4e070",
    isActive: true,
    balance: "$1,700.35",
    picture: "http://placehold.it/32x32",
    age: 32,
    eyeColor: "blue",
    name: "Sherman Riggs",
    gender: "male",
    company: "ZAJ",
    email: "shermanriggs@zaj.com",
    phone: "+1 (964) 481-2801",
    address:
      "140 Debevoise Street, Cressey, Federated States Of Micronesia, 9160",
    about:
      "Nulla irure eu ad dolor officia sit minim elit anim in aute aliqua id. Quis ullamco do esse labore ex amet aliquip magna. Adipisicing ad incididunt officia enim excepteur irure occaecat. Officia pariatur cillum sit reprehenderit eiusmod consequat ipsum velit enim. Laborum velit culpa occaecat deserunt. Enim id et occaecat duis deserunt et. Ad commodo eiusmod ullamco magna irure voluptate aliqua officia eiusmod do anim consequat mollit minim.\r\n",
    registered: "2021-01-30T05:54:57 -06:-45",
    latitude: 5.528223,
    longitude: 93.425396,
    tags: [
      "incididunt",
      "culpa",
      "cupidatat",
      "sint",
      "ut",
      "officia",
      "nulla",
    ],
    friends: [
      {
        id: 0,
        name: "Curtis Lynn",
      },
      {
        id: 1,
        name: "Cherie Mercer",
      },
      {
        id: 2,
        name: "Teresa Wilder",
      },
    ],
    greeting: "Hello, Sherman Riggs! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "63e10d4158605cd5057789b7",
    index: 2,
    guid: "ee52418e-4514-4db9-885e-87d1de2499af",
    isActive: true,
    balance: "$3,588.30",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "brown",
    name: "Katy Soto",
    gender: "female",
    company: "NETAGY",
    email: "katysoto@netagy.com",
    phone: "+1 (846) 496-3683",
    address: "751 Moore Street, Oberlin, North Carolina, 6769",
    about:
      "Ullamco exercitation ut excepteur qui excepteur laborum ut exercitation sint exercitation non et nisi fugiat. Officia aliqua est consequat proident id dolor aliquip. Et est aliquip laborum magna fugiat veniam anim culpa ex nostrud culpa ad in ipsum. Cillum dolore proident aute anim ullamco nulla dolore nulla cupidatat deserunt. Pariatur nisi exercitation eu nisi eu mollit ut dolor. Minim occaecat officia excepteur ex laboris deserunt velit voluptate.\r\n",
    registered: "2019-01-11T09:08:58 -06:-45",
    latitude: 46.483534,
    longitude: 173.22756,
    tags: ["labore", "qui", "esse", "sit", "sint", "laborum", "ipsum"],
    friends: [
      {
        id: 0,
        name: "Mcfadden Mueller",
      },
      {
        id: 1,
        name: "Cleo Workman",
      },
      {
        id: 2,
        name: "Dean Weaver",
      },
    ],
    greeting: "Hello, Katy Soto! You have 4 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "63e10d41f181f96e21a1a948",
    index: 3,
    guid: "40f328d6-0f07-4974-990a-6267a1b5a924",
    isActive: true,
    balance: "$1,399.95",
    picture: "http://placehold.it/32x32",
    age: 34,
    eyeColor: "green",
    name: "Huffman Middleton",
    gender: "male",
    company: "INTRAWEAR",
    email: "huffmanmiddleton@intrawear.com",
    phone: "+1 (996) 591-2824",
    address: "989 Dahlgreen Place, Utting, Delaware, 7057",
    about:
      "Sunt id labore esse quis mollit ad non. Anim aute anim officia est ad magna id proident ipsum ullamco amet cupidatat nostrud sunt. Pariatur consectetur reprehenderit aliqua est laborum eu laboris esse ut ut et nulla dolore. Ipsum minim quis amet dolore aliqua amet quis dolore sit amet ipsum irure nostrud. Velit irure adipisicing esse elit occaecat officia ut laboris irure nostrud. Mollit cupidatat in amet commodo labore aute laboris minim.\r\n",
    registered: "2018-03-27T08:47:59 -06:-45",
    latitude: 46.937758,
    longitude: -92.964184,
    tags: [
      "esse",
      "non",
      "consequat",
      "occaecat",
      "nostrud",
      "labore",
      "consequat",
    ],
    friends: [
      {
        id: 0,
        name: "Jimmie English",
      },
      {
        id: 1,
        name: "Ladonna Roach",
      },
      {
        id: 2,
        name: "Valarie Oliver",
      },
    ],
    greeting: "Hello, Huffman Middleton! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "63e10d41059823c089baf7d4",
    index: 4,
    guid: "5f8d21ea-df68-4eed-805d-5d165eddc75f",
    isActive: false,
    balance: "$2,346.56",
    picture: "http://placehold.it/32x32",
    age: 25,
    eyeColor: "green",
    name: "Heath Rush",
    gender: "male",
    company: "STROZEN",
    email: "heathrush@strozen.com",
    phone: "+1 (976) 509-3580",
    address: "476 Cadman Plaza, Chamberino, Tennessee, 4726",
    about:
      "Consequat do ipsum velit exercitation exercitation id sit. Excepteur magna non excepteur ut eiusmod anim sunt aliqua irure qui consequat sint sunt do. Cillum minim sunt id tempor excepteur occaecat sunt tempor. Duis deserunt proident quis magna deserunt duis deserunt fugiat. Enim eu Lorem do duis.\r\n",
    registered: "2022-04-11T05:37:42 -06:-45",
    latitude: -22.452499,
    longitude: 39.403714,
    tags: [
      "reprehenderit",
      "qui",
      "eiusmod",
      "et",
      "laborum",
      "enim",
      "veniam",
    ],
    friends: [
      {
        id: 0,
        name: "Jean Mcdonald",
      },
      {
        id: 1,
        name: "Sampson Morgan",
      },
      {
        id: 2,
        name: "Cherry Mullen",
      },
    ],
    greeting: "Hello, Heath Rush! You have 2 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "63e10d41be749f8724b636b0",
    index: 5,
    guid: "0376eb8c-00b6-4620-b9f0-1dcf97f1b9e5",
    isActive: false,
    balance: "$2,345.60",
    picture: "http://placehold.it/32x32",
    age: 38,
    eyeColor: "green",
    name: "Nelda Guzman",
    gender: "female",
    company: "HALAP",
    email: "neldaguzman@halap.com",
    phone: "+1 (984) 535-3929",
    address: "480 Emerson Place, Gerber, Texas, 4586",
    about:
      "Do ipsum minim est velit consequat ut. Anim duis ea commodo tempor exercitation aute aute sit laborum dolore ex consectetur. Eiusmod non aliqua dolor excepteur elit nisi. Veniam voluptate tempor culpa sint veniam laboris voluptate mollit nulla sit nostrud eiusmod proident nostrud. Sint anim nulla qui aute non tempor exercitation anim do irure esse enim magna. Commodo laborum cillum nostrud velit cillum cillum voluptate ex magna reprehenderit ipsum aliquip ipsum magna. Ad magna est nisi ipsum anim duis deserunt laboris ex.\r\n",
    registered: "2015-05-17T12:28:22 -06:-45",
    latitude: 24.859629,
    longitude: 57.979968,
    tags: [
      "culpa",
      "proident",
      "amet",
      "exercitation",
      "voluptate",
      "labore",
      "pariatur",
    ],
    friends: [
      {
        id: 0,
        name: "Nunez Schultz",
      },
      {
        id: 1,
        name: "Marietta Alston",
      },
      {
        id: 2,
        name: "Jayne Vazquez",
      },
    ],
    greeting: "Hello, Nelda Guzman! You have 2 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "63e10d41183a8185b7aff617",
    index: 6,
    guid: "a9e8019b-6827-4fa9-a4df-218f15404b5b",
    isActive: true,
    balance: "$2,755.37",
    picture: "http://placehold.it/32x32",
    age: 36,
    eyeColor: "green",
    name: "Shauna Tran",
    gender: "female",
    company: "IMPERIUM",
    email: "shaunatran@imperium.com",
    phone: "+1 (980) 461-3169",
    address: "601 Dunne Place, Itmann, Minnesota, 2101",
    about:
      "Ut culpa mollit voluptate ea aliquip deserunt cillum sit commodo. Occaecat velit consectetur irure fugiat aliquip consectetur laborum velit nostrud qui Lorem nulla. Ea quis labore reprehenderit magna duis voluptate ea occaecat ex nisi id quis anim. Magna enim eiusmod laboris aute in mollit dolore laboris consectetur nisi incididunt irure consectetur consectetur. Adipisicing in cupidatat aliqua proident laborum exercitation cillum tempor eu aliquip quis eiusmod nostrud proident. Excepteur sunt sit sit officia Lorem sit enim.\r\n",
    registered: "2014-02-23T04:09:18 -06:-45",
    latitude: 64.53278,
    longitude: 158.214849,
    tags: [
      "exercitation",
      "occaecat",
      "laboris",
      "non",
      "laboris",
      "sint",
      "irure",
    ],
    friends: [
      {
        id: 0,
        name: "Humphrey Nichols",
      },
      {
        id: 1,
        name: "Buckner Klein",
      },
      {
        id: 2,
        name: "Carissa Harding",
      },
    ],
    greeting: "Hello, Shauna Tran! You have 7 unread messages.",
    favoriteFruit: "apple",
  },
];
